In [2]:
import pandas as pd

In [ ]:
cond = pd.read_csv('synthea_lungca/records/conditions.csv')
obs = pd.read_csv('synthea_lungca/records/observations.csv')

In [31]:
enc = pd.read_csv('synthea_lungca/records/encounters.csv')

In [36]:
cond[cond.DESCRIPTION == "Non-small cell lung cancer (disorder)"]

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION
1539,2007-08-23,NaN,1fd51f60-07af-4546-4a3d-9a01db77e97a,a871cf68-3aea-7562-0a2e-3d657a33240a,254637007,Non-small cell lung cancer (disorder)
4078,1984-12-11,NaN,d519a453-e39b-bf5d-2f76-b4515ab448cb,542bbba2-3c2e-c65b-de38-cf31198459cb,254637007,Non-small cell lung cancer (disorder)
4823,1995-06-13,NaN,1f0914f9-7d12-8562-c290-1b9141b28de1,8f66332b-c8fc-edfd-9531-f8f6eea0fb03,254637007,Non-small cell lung cancer (disorder)
5616,1996-07-22,NaN,0fdcb4dd-8f6e-551b-9c70-c7eb16e695f7,5cdb8a86-076e-c4da-d204-703ebfdc8a67,254637007,Non-small cell lung cancer (disorder)
6070,1993-05-01,NaN,2961bfb0-2af5-da27-954a-e91392face7e,a9d73917-82f0-d610-7605-804d481751e5,254637007,Non-small cell lung cancer (disorder)
...,...,...,...,...,...,...
865071,2010-03-12,NaN,df8aaaeb-c8a0-908d-48b9-0761f91f5a5b,ae469d6b-6453-c021-1ffe-3abe0d8c6f84,254637007,Non-small cell lung cancer (disorder)
869961,2004-11-01,NaN,b274bed8-e041-29c3-7bb6-c740c57a042a,5d15245a-c2e0-5b18-38fc-3d5f84551a65,254637007,Non-small cell lung cancer (disorder)
870217,1987-03-22,NaN,ad4cfe3c-6cf0-bc9d-2470-131165158728,3722f482-d8ca-16b9-7c4d-9ae67647de73,254637007,Non-small cell lung cancer (disorder)
870632,2007-01-29,NaN,d0abdc9e-cbef-2358-99f4-abcba316952e,6b70d163-a045-93e9-2136-afae82f1f836,254637007,Non-small cell lung cancer (disorder)
871479,1996-10-02,NaN,00a08e23-ab44-138f-ece8-b360839411e7,c1e2412f-4a8b-af31-4a9a-a40a85482318,254637007,Non-small cell lung cancer (disorder)

In [65]:
pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/emar.csv.gz')

,subject_id,hadm_id,emar_id,emar_seq,poe_id,pharmacy_id,enter_provider_id,charttime,medication,event_txt,scheduletime,storetime
0,10005909,20199380.0,10005909-74,74,10005909-97,96110427.0,NaN,2144-10-31 05:56:00,Magnesium Sulfate,NaN,2144-10-31 05:56:00,2144-10-31 05:56:00
1,10005909,20199380.0,10005909-79,79,10005909-97,96110427.0,NaN,2144-10-31 08:00:00,Magnesium Sulfate,NaN,2144-10-31 08:00:00,2144-10-31 08:15:00
2,10008287,22168393.0,10008287-32,32,10008287-58,NaN,P26PKF,2145-09-28 20:15:00,Potassium Chloride Replacement (Critical Care ...,NaN,2145-09-28 20:15:00,2145-09-28 20:38:00
3,10010471,21322534.0,10010471-33,33,10010471-51,52131847.0,NaN,2155-05-08 21:45:00,Metoprolol Tartrate,NaN,2155-05-08 21:45:00,2155-05-08 22:40:00
4,10015272,27993466.0,10015272-31,31,10015272-48,88758875.0,NaN,2137-06-13 08:36:00,Metoprolol Tartrate,NaN,2137-06-13 08:36:00,2137-06-13 08:36:00
...,...,...,...,...,...,...,...,...,...,...,...,...
35830,10037861,24540843.0,10037861-371,371,10037861-385,NaN,NaN,2117-03-17 19:00:00,Midazolam,Infusion Reconciliation Not Done,2117-03-17 19:00:00,2117-03-17 18:33:00
35831,10018423,29366372.0,10018423-20,20,10018423-64,NaN,P401QD,2167-05-04 17:00:00,Heparin,Stopped - Unscheduled in Other Location,2167-05-04 17:00:00,2167-05-04 18:19:00
35832,10014354,28335091.0,10014354-259,259,10014354-301,NaN,NaN,2147-04-28 17:00:00,Heparin,Stopped - Unscheduled in Other Location,2106-09-29 00:00:00,2147-04-28 22:34:00
35833,10019003,27525946.0,10019003-255,255,10019003-538,NaN,NaN,2153-04-14 17:00:00,PHENYLEPHrine,Stopped - Unscheduled in Other Location,2153-04-14 17:00:00,2153-04-15 02:28:00
35834,10029291,22205327.0,10029291-530,530,10029291-400,NaN,NaN,2123-03-03 18:00:00,NaN,Stopped - Unscheduled in Other Location,2123-03-03 18:00:00,2123-03-04 06:26:00

In [74]:
dx = pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/diagnoses_icd.csv.gz')

In [85]:
pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/hcpcsevents.csv.gz').sort_values(['subject_id', 'seq_num'])

,subject_id,hadm_id,chartdate,hcpcs_cd,seq_num,short_description
15,10002428,28676446,2157-07-16,27235,1,Musculoskeletal system
44,10002428,25797028,2155-07-14,G0378,1,Hospital observation per hr
45,10002428,26549334,2160-07-15,G0378,1,Hospital observation per hr
46,10002428,28676446,2157-07-16,G0378,2,Hospital observation per hr
36,10002930,22380825,2193-08-05,G0378,1,Hospital observation per hr
...,...,...,...,...,...,...
56,10039708,27504040,2142-07-06,99219,3,Hospital observation services
13,10039708,27504040,2142-07-06,36830,4,Cardiovascular system
31,10039997,21390688,2135-11-07,G0378,1,Hospital observation per hr
14,10040025,27125816,2143-03-18,36252,1,Cardiovascular system
60,10040025,27125816,2143-03-18,99218,2,Hospital observation services

In [90]:
pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/hcpcsevents.csv.gz').sort_values(['subject_id', 'chartdate']).head(20)

,subject_id,hadm_id,chartdate,hcpcs_cd,seq_num,short_description
44,10002428,25797028,2155-07-14,G0378,1,Hospital observation per hr
15,10002428,28676446,2157-07-16,27235,1,Musculoskeletal system
46,10002428,28676446,2157-07-16,G0378,2,Hospital observation per hr
45,10002428,26549334,2160-07-15,G0378,1,Hospital observation per hr
36,10002930,22380825,2193-08-05,G0378,1,Hospital observation per hr
39,10002930,28477649,2197-04-07,G0378,1,Hospital observation per hr
40,10002930,25282382,2197-04-17,G0378,1,Hospital observation per hr
41,10002930,23720373,2199-02-17,G0378,1,Hospital observation per hr
38,10002930,28697806,2200-06-05,G0378,1,Hospital observation per hr
37,10002930,20846853,2201-02-12,G0378,1,Hospital observation per hr
42,10002930,20282368,2201-03-23,G0378,1,Hospital observation per hr
2,10004457,21039249,2140-09-17,92980,1,Cardiovascular
35,10004457,21039249,2140-09-17,G0378,2,Hospital observation per hr
3,10004457,25559382,2148-09-14,93455,1,Cardiovascular
34,10004457,25559382,2148-09-14,G0378,3,Hospital observation per hr
48,10004457,25559382,2148-09-14,C9600,2,Perc drug-el cor stent sing
0,10005348,29176490,2129-05-22,93454,1,Cardiovascular
1,10005348,29176490,2129-05-22,92921,2,Cardiovascular
18,10005348,29176490,2129-05-22,G0378,4,Hospital observation per hr
47,10005348,29176490,2129-05-22,C9600,3,Perc drug-el cor stent sing

In [88]:
pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/admissions.csv.gz').sort_values(['subject_id']).head(20)

,subject_id,hadm_id,admittime,dischtime,deathtime,admission_type,admit_provider_id,admission_location,discharge_location,insurance,language,marital_status,race,edregtime,edouttime,hospital_expire_flag
18,10000032,22595853,2180-05-06 22:23:00,2180-05-07 17:15:00,NaN,URGENT,P874LG,TRANSFER FROM HOSPITAL,HOME,Other,ENGLISH,WIDOWED,WHITE,2180-05-06 19:17:00,2180-05-06 23:30:00,0
103,10000032,22841357,2180-06-26 18:27:00,2180-06-27 18:49:00,NaN,EW EMER.,P09Q6Y,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-06-26 15:54:00,2180-06-26 21:31:00,0
104,10000032,25742920,2180-08-05 23:44:00,2180-08-07 17:50:00,NaN,EW EMER.,P60CC5,EMERGENCY ROOM,HOSPICE,Medicaid,ENGLISH,WIDOWED,WHITE,2180-08-05 20:58:00,2180-08-06 01:44:00,0
105,10000032,29079034,2180-07-23 12:35:00,2180-07-25 17:55:00,NaN,EW EMER.,P30KEH,EMERGENCY ROOM,HOME,Medicaid,ENGLISH,WIDOWED,WHITE,2180-07-23 05:54:00,2180-07-23 14:00:00,0
157,10001217,27703517,2157-12-18 16:58:00,2157-12-24 14:55:00,NaN,DIRECT EMER.,P99698,PHYSICIAN REFERRAL,HOME HEALTH CARE,Other,?,MARRIED,WHITE,NaN,NaN,0
65,10001217,24597018,2157-11-18 22:56:00,2157-11-25 18:00:00,NaN,EW EMER.,P4645A,EMERGENCY ROOM,HOME HEALTH CARE,Other,?,MARRIED,WHITE,2157-11-18 17:38:00,2157-11-19 01:24:00,0
64,10001725,25563031,2110-04-11 15:08:00,2110-04-14 15:00:00,NaN,EW EMER.,P35SU0,PACU,HOME,Other,ENGLISH,MARRIED,WHITE,NaN,NaN,0
199,10002428,26549334,2160-07-15 23:37:00,2160-07-16 18:49:00,NaN,EU OBSERVATION,P607HY,EMERGENCY ROOM,NaN,Medicare,ENGLISH,WIDOWED,WHITE,2160-07-15 17:34:00,2160-07-16 18:49:00,0
197,10002428,28676446,2157-07-16 04:09:00,2157-07-18 16:49:00,NaN,EU OBSERVATION,P08S8F,EMERGENCY ROOM,NaN,Medicare,ENGLISH,WIDOWED,WHITE,2157-07-16 01:50:00,2157-07-16 09:51:00,0
152,10002428,28662225,2156-04-12 14:16:00,2156-04-29 16:26:00,NaN,EW EMER.,P64TOH,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,ENGLISH,WIDOWED,WHITE,2156-04-12 09:56:00,2156-04-12 17:11:00,0
153,10002428,20321825,2156-04-30 20:35:00,2156-05-03 16:36:00,NaN,EW EMER.,P825SO,EMERGENCY ROOM,CHRONIC/LONG TERM ACUTE CARE,Medicare,ENGLISH,WIDOWED,WHITE,2156-04-30 18:30:00,2156-04-30 21:53:00,0
154,10002428,23473524,2156-05-11 14:49:00,2156-05-22 14:16:00,NaN,EW EMER.,P3529J,EMERGENCY ROOM,CHRONIC/LONG TERM ACUTE CARE,Medicare,ENGLISH,WIDOWED,WHITE,2156-05-11 11:29:00,2156-05-11 16:53:00,0
244,10002428,28295257,2160-04-14 12:30:00,2160-04-18 16:00:00,NaN,OBSERVATION ADMIT,P18I28,EMERGENCY ROOM,SKILLED NURSING FACILITY,Medicare,ENGLISH,WIDOWED,WHITE,2160-04-14 09:01:00,2160-04-14 14:28:00,0
198,10002428,25797028,2155-07-14 19:15:00,2155-07-15 18:37:00,NaN,EU OBSERVATION,P64TOH,EMERGENCY ROOM,NaN,Medicare,ENGLISH,WIDOWED,WHITE,2155-07-14 16:58:00,2155-07-14 20:04:00,0
7,10002495,24982426,2141-05-22 20:17:00,2141-05-29 17:41:00,NaN,URGENT,P79SJ2,TRANSFER FROM HOSPITAL,SKILLED NURSING FACILITY,Medicare,ENGLISH,MARRIED,UNKNOWN,NaN,NaN,0
168,10002930,23688993,2193-08-05 11:45:00,2193-08-11 09:25:00,NaN,DIRECT EMER.,P356OC,PHYSICIAN REFERRAL,HOME,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2193-08-05 05:04:00,2193-08-05 12:00:00,0
147,10002930,25696644,2196-04-14 12:25:00,2196-04-17 15:28:00,NaN,EW EMER.,P43A1R,EMERGENCY ROOM,PSYCH FACILITY,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2196-04-14 05:55:00,2196-04-14 13:40:00,0
146,10002930,25922998,2198-04-17 19:38:00,2198-04-22 16:02:00,NaN,EW EMER.,P30KEH,EMERGENCY ROOM,PSYCH FACILITY,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2198-04-17 11:42:00,2198-04-17 21:24:00,0
32,10002930,28301173,2197-04-08 19:37:00,2197-04-15 12:01:00,NaN,URGENT,P3763P,INTERNAL TRANSFER TO OR FROM PSYCH,HOME,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,NaN,NaN,0
190,10002930,25282382,2197-04-17 02:01:00,2197-04-17 09:48:00,NaN,EU OBSERVATION,P33NK4,EMERGENCY ROOM,NaN,Medicare,ENGLISH,SINGLE,BLACK/AFRICAN AMERICAN,2197-04-16 22:57:00,2197-04-17 09:48:00,0

In [98]:
icd_map = pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/d_icd_diagnoses.csv.gz')[['icd_code', 'long_title']].set_index('icd_code')

In [111]:
icd_map.loc(dx.icd_code)

TypeError: unhashable type: 'Series'

In [115]:
icd_map.loc[dx.icd_code]

                                                 long_title
icd_code
4139                  Other and unspecified angina pectoris
V707           Examination of participant in clinical trial
V707      Person on outside of bus injured in collision ...
41401     Coronary atherosclerosis of native coronary ar...
3899                               Unspecified hearing loss
...                                                     ...
3129                     Unspecified disturbance of conduct
30000                            Anxiety state, unspecified
4739                        Unspecified sinusitis (chronic)
56210     Diverticulosis of colon (without mention of he...
30390     Other and unspecified alcohol dependence, unsp...

[4594 rows x 1 columns]

In [127]:
[k for k in pd.DataFrame(dx.sort_values(['subject_id', 'seq_num']).icd_code.value_counts().sort_values(ascending=False)).join(icd_map).long_title if "lung" in k]

['Acute edema of lung, unspecified',
 'Family history of malignant neoplasm of trachea, bronchus, and lung',
 'Other diseases of lung, not elsewhere classified',
 'Secondary malignant neoplasm of lung',
 'Malignant neoplasm of bronchus and lung, unspecified',
 'Personal history of malignant neoplasm of bronchus and lung',
 'Malignant neoplasm of lower lobe, bronchus or lung',
 'Other nonspecific abnormal finding of lung field',
 'Contusion of lung without mention of open wound into thorax',
 'Other nonspecific abnormal finding of lung field',
 'Malignant neoplasm of unspecified part of unspecified bronchus or lung',
 'Family history of malignant neoplasm of trachea, bronchus and lung',
 'Transfusion related acute lung injury (TRALI)']

In [ ]:
dx

      subject_id   hadm_id  seq_num icd_code  icd_version
0       10035185  22580999        3     4139            9
1       10035185  22580999       10     V707            9
2       10035185  22580999        1    41401            9
3       10035185  22580999        9     3899            9
4       10035185  22580999       11    V8532            9
...          ...       ...      ...      ...          ...
4501    10004733  27411876       19     3129            9
4502    10004733  27411876       30    30000            9
4503    10004733  27411876       26     4739            9
4504    10004733  27411876       22    56210            9
4505    10004733  27411876       29    30390            9

[4506 rows x 5 columns]

In [ ]:
ddx = pd.read_csv('mimic/mimic-iv-ed-2.2/ed/diagnosis.csv.gz')
triage =  pd.read_csv('mimic/mimic-iv-ed-2.2/ed/triage.csv.gz')
edstays = pd.read_csv('mimic/mimic-iv-ed-2.2/ed/edstays.csv.gz')

In [4]:
edstays

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,F,WHITE,AMBULANCE,ADMITTED
1,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,F,WHITE,AMBULANCE,ADMITTED
2,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,F,WHITE,AMBULANCE,ADMITTED
3,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,F,WHITE,AMBULANCE,HOME
4,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,F,WHITE,AMBULANCE,ADMITTED
...,...,...,...,...,...,...,...,...,...
425082,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,M,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED
425083,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,F,WHITE,AMBULANCE,ADMITTED
425084,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,F,WHITE,WALK IN,ADMITTED
425085,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:56:00,F,UNKNOWN,UNKNOWN,ELOPED
425086,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,F,UNKNOWN,AMBULANCE,ADMITTED

In [115]:
c = triage[triage.chiefcomplaint.isin([t for t in triage.chiefcomplaint if 'cough' in str(t).lower()])].subject_id.value_counts()
cs = c[c > 1].index

In [118]:
triage[triage.subject_id.isin(cs)]

,subject_id,stay_id,temperature,heartrate,resprate,o2sat,sbp,dbp,pain,acuity,chiefcomplaint
71,10001884,31306678,NaN,NaN,NaN,79.0,NaN,NaN,unable,1.0,Hypoxia
72,10001884,31742950,97.6,67.0,22.0,97.0,132.0,82.0,0,2.0,Dyspnea
73,10001884,33281437,98.2,72.0,20.0,97.0,157.0,66.0,2,3.0,CP/SOB
74,10001884,33478776,98.4,74.0,16.0,100.0,142.0,69.0,0,3.0,"Dyspnea, Fatigue"
75,10001884,34226385,98.2,65.0,18.0,97.0,113.0,91.0,0,2.0,Dyspnea
...,...,...,...,...,...,...,...,...,...,...,...
424220,19978087,34430061,97.3,68.0,17.0,100.0,121.0,77.0,3,3.0,"Chest pain, Cough"
424221,19978087,35192373,97.8,71.0,16.0,100.0,112.0,68.0,9,2.0,"Back pain, R Leg pain"
424222,19978087,35758997,97.8,104.0,18.0,99.0,109.0,76.0,0,3.0,COUGH
424223,19978087,35903340,97.7,91.0,16.0,100.0,121.0,75.0,10,3.0,Headache
424224,19978087,38118978,97.1,77.0,18.0,100.0,127.0,85.0,10,4.0,Lower back pain

In [119]:
edstays[edstays.subject_id.isin(cs)]

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
71,10001884,21192799.0,38708413,2130-10-05 11:58:00,2130-10-06 15:05:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
72,10001884,22532141.0,38021228,2130-10-13 21:00:00,2130-10-14 13:57:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
73,10001884,24325811.0,33281437,2126-11-03 19:15:00,2126-11-04 12:49:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
74,10001884,24746267.0,35329716,2130-12-27 15:48:00,2130-12-27 22:30:00,F,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED
75,10001884,24962904.0,31742950,2130-12-06 16:46:00,2130-12-06 22:05:00,F,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED
...,...,...,...,...,...,...,...,...,...
424220,19978087,NaN,34430061,2146-05-12 13:45:00,2146-05-12 17:02:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
424221,19978087,NaN,35192373,2144-05-16 08:02:00,2144-05-16 13:05:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
424222,19978087,NaN,35758997,2139-11-13 09:52:00,2139-11-13 13:21:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
424223,19978087,NaN,35903340,2143-01-04 11:40:00,2143-01-04 14:14:00,F,BLACK/AFRICAN AMERICAN,WALK IN,HOME
424224,19978087,NaN,38118978,2144-05-15 11:18:00,2144-05-15 13:38:00,F,BLACK/AFRICAN AMERICAN,UNKNOWN,LEFT WITHOUT BEING SEEN

In [132]:
[n for n in ddx[ddx.subject_id.isin(cs)].icd_title if 'neoplasm' in str(n).lower()]

['Personal history of malignant neoplasm of breast',
 'Malignant neoplasm of rectum',
 'BONE/SKIN NEOPLASM NOS',
 'Malignant neoplasm of prostate',
 'Secondary malignant neoplasm of bone',
 'Malignant neoplasm of endometrium',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Secondary malignant neoplasm of brain',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Secondary malignant neoplasm of unspecified lung',
 'Personal history of malignant neoplasm of esophagus',
 'Personal history of malignant neoplasm of breast',
 'Malignant neoplasm of colon, unspecified',
 'Secondary malignant neoplasm of retroperiton and peritoneum',
 'Malignant neoplasm of unsp site of unspecified female breast',
 'Personal history of malignant neoplasm of bronchus and lung',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Secondary malignant neoplasm of brain',
 'Malignant neoplasm of unsp site of unspecified female breast',
 'Secondary malignant neoplasm of bone',
 'Malignant neoplasm of unsp site of unspecified female breast',
 'Secondary malignant neoplasm of bone',
 'Malignant neoplasm of upper lobe, left bronchus or lung',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Personal history of malignant neoplasm of ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Neoplasm related pain (acute) (chronic)',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Malignant neoplasm of unspecified ovary',
 'Personal history of malignant neoplasm of ovary',
 'MALIG NEOPLASM MOUTH NOS',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of colon, unspecified',
 'Secondary malig neoplasm of liver and intrahepatic bile duct',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of rectum',
 'Secondary malig neoplasm of liver and intrahepatic bile duct',
 'Personal history of other malignant neoplasm of kidney',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Secondary malignant neoplasm of brain',
 'Secondary malignant neoplasm of unsp kidney and renal pelvis',
 'Secondary malignant neoplasm of brain',
 'Malignant neoplasm of other cranial nerves',
 'Malignant neoplasm of hypopharynx, unspecified',
 'Malignant neoplasm of esophagus, unspecified',
 'Personal history of malignant neoplasm of larynx',
 'Malignant neoplasm of unsp part of unsp bronchus or lung']

In [77]:
triage.chiefcomplaint

0                                      Hypotension
1                   Abd pain, Abdominal distention
2                                  n/v/d, Abd pain
3                             Abdominal distention
4         Abdominal distention, Abd pain, LETHAGIC
                            ...
425082                                Abnormal MRI
425083                        Abd pain, Wound eval
425084                        Abd pain, Wound eval
425085        Altered mental status, Substance use
425086                                  HEAD BLEED
Name: chiefcomplaint, Length: 425087, dtype: object

In [71]:
triage.chiefcomplaint.value_counts().head(50)

chiefcomplaint
Chest pain                  11301
Abd pain                    10771
Dyspnea                      6003
s/p Fall                     4965
ABD PAIN                     4957
SI                           4926
ETOH                         4679
Wound eval                   4509
Headache                     3828
Back pain                    3166
MVC                          3134
Altered mental status        2688
Lower back pain              2630
S/P FALL                     2579
CHEST PAIN                   2577
N/V                          2497
Syncope                      2301
BRBPR                        2294
Dizziness                    2238
Weakness                     2233
Fever                        2226
ILI                          2137
Abd pain, N/V                2094
ABDOMINAL PAIN               1992
Chest pain, Dyspnea          1983
Abnormal labs                1908
Seizure                      1874
RLQ abdominal pain           1772
Rash                         1697
BACK PAIN                    1683
Sore throat                  1624
Palpitations                 1609
Abd pain, Transfer           1557
Allergic reaction            1495
ETOH, Unable to ambulate     1412
DYSPNEA                      1398
Cough                        1362
CP                           1338
FEVER                        1331
SOB                          1330
HEADACHE                     1277
n/v/d                        1262
___                          1252
R Flank pain                 1160
R Knee pain                  1148
L Flank pain                 1130
L Knee pain                  1119
Anxiety                      1073
RUQ abdominal pain           1072
Dysuria                      1048
Name: count, dtype: int64

In [294]:
set([c for c in ddx.icd_title if 'lung' in c.lower() and 'neoplasm' in c.lower()])

{'Malignant neoplasm of lower lobe, left bronchus or lung',
 'Malignant neoplasm of lower lobe, right bronchus or lung',
 'Malignant neoplasm of middle lobe, bronchus or lung',
 'Malignant neoplasm of unsp part of left bronchus or lung',
 'Malignant neoplasm of unsp part of right bronchus or lung',
 'Malignant neoplasm of unsp part of unsp bronchus or lung',
 'Malignant neoplasm of upper lobe, left bronchus or lung',
 'Malignant neoplasm of upper lobe, right bronchus or lung',
 'Personal history of malignant neoplasm of bronchus and lung',
 'Secondary malignant neoplasm of left lung',
 'Secondary malignant neoplasm of right lung',
 'Secondary malignant neoplasm of unspecified lung'}

In [30]:
triage[triage.chiefcomplaint == 'Chest pain']

,subject_id,stay_id,temperature,heartrate,resprate,o2sat,sbp,dbp,pain,acuity,chiefcomplaint
45,10018423,39057874,98.2,84.0,16.0,98.0,142.0,97.0,6,2.0,Chest pain
48,10014354,39394858,98.3,83.0,20.0,98.0,159.0,105.0,9,2.0,Chest pain
74,10023117,35716124,96.8,115.0,18.0,97.0,95.0,65.0,0,2.0,Chest pain
108,10014354,32287800,97.9,62.0,16.0,95.0,145.0,63.0,9,2.0,Chest pain
179,10009049,31628990,99.0,87.0,18.0,96.0,126.0,68.0,0,3.0,Chest pain

In [44]:
ddx[ddx.subject_id==10023117].sort_values('seq_num')

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title
401,10023117,35087345,1,4280,9,"CONGESTIVE HEART FAILURE, UNSPEC"
402,10023117,31283645,1,4280,9,"CONGESTIVE HEART FAILURE, UNSPEC"
404,10023117,39898790,1,5849,9,"ACUTE KIDNEY FAILURE, UNSPECIFIED"
405,10023117,35716124,1,R079,10,"Chest pain, unspecified"
406,10023117,31588683,1,78609,9,RESPIRATORY ABNORM NEC
399,10023117,35087345,2,2720,9,HYPERCHOLESTEROLEMIA
400,10023117,31588683,2,4019,9,HYPERTENSION NOS
403,10023117,39898790,2,4280,9,"CONGESTIVE HEART FAILURE, UNSPEC"
407,10023117,31588683,3,V4501,9,CARDIAC PACEMAKER STATUS

In [37]:
edstays[edstays.subject_id==10023117].sort_values('intime')

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
209,10023117,NaN,31588683,2171-10-12 11:33:00,2171-10-12 14:33:00,M,WHITE,WALK IN,HOME
213,10023117,28872262.0,31283645,2171-11-07 17:40:00,2171-11-07 22:50:00,M,WHITE,AMBULANCE,ADMITTED
211,10023117,29858644.0,35087345,2173-04-16 17:00:00,2173-04-16 23:18:00,M,WHITE,WALK IN,ADMITTED
212,10023117,24244087.0,39898790,2174-06-07 16:24:00,2174-06-08 01:02:00,M,WHITE,AMBULANCE,ADMITTED
210,10023117,21607814.0,35716124,2175-07-06 14:02:00,2175-07-06 17:41:00,M,WHITE,AMBULANCE,ADMITTED

In [39]:
dc = pd.read_csv('mimic/mimic-iv-notes-2.2/note/discharge.csv.gz')

In [41]:
dc_details = pd.read_csv('mimic/mimic-iv-notes-2.2/note/discharge_detail.csv.gz')

In [137]:
dc

,note_id,subject_id,hadm_id,note_type,note_seq,charttime,storetime,text
0,10000032-DS-21,10000032,22595853,DS,21,2180-05-07 00:00:00,2180-05-09 15:26:00,\nName: ___ Unit No: _...
1,10000032-DS-22,10000032,22841357,DS,22,2180-06-27 00:00:00,2180-07-01 10:15:00,\nName: ___ Unit No: _...
2,10000032-DS-23,10000032,29079034,DS,23,2180-07-25 00:00:00,2180-07-25 21:42:00,\nName: ___ Unit No: _...
3,10000032-DS-24,10000032,25742920,DS,24,2180-08-07 00:00:00,2180-08-10 05:43:00,\nName: ___ Unit No: _...
4,10000084-DS-17,10000084,23052089,DS,17,2160-11-25 00:00:00,2160-11-25 15:09:00,\nName: ___ Unit No: __...
...,...,...,...,...,...,...,...,...
331788,19999828-DS-6,19999828,29734428,DS,6,2147-08-04 00:00:00,2147-08-12 15:36:00,\nName: ___ Unit No: ___...
331789,19999828-DS-7,19999828,25744818,DS,7,2149-01-18 00:00:00,2149-01-19 07:03:00,\nName: ___ Unit No: ___...
331790,19999840-DS-20,19999840,26071774,DS,20,2164-07-28 00:00:00,2164-07-29 14:52:00,\nName: ___ Unit No: ___\...
331791,19999840-DS-21,19999840,21033226,DS,21,2164-09-17 00:00:00,2164-09-18 01:36:00,\nName: ___ Unit No: ___\...
331792,19999987-DS-2,19999987,23865745,DS,2,2145-11-11 00:00:00,2145-11-11 13:13:00,\nName: ___ Unit No: __...

In [53]:
print(dc[dc.subject_id==10023117].sort_values('note_seq').text[756])

Name:  ___               Unit No:   ___

Admission Date:  ___              Discharge Date:   ___

Date of Birth:  ___             Sex:   M

Service: MEDICINE

Allergies:
Clozaril / Tegretol / Benadryl

Attending: ___.

Chief Complaint:
Shortness of breath

Major Surgical or Invasive Procedure:
Right heart catheterization ___
Left thoracotomy with left ventricular pacing wire placement
___

History of Present Illness:
Pt ___ w h/o non-ischemic cardiomyopathy (EF ___ ___ ___
attributed to  an anti-psychotic medication. He had marked left
ventricular  mechanical dyssynchrony due to wide left
bundle-branch block. He has a biventricular pacer ___ place, but
the left ventricular lead  was causing significant chest wall
stimulation. Percutaneous  attempt was made at re-positioning
the lead, however
unsuccessful so is ___ the process of being evaluated for pacer
revision by CT surg.
.
Presented to ___ with a chief complaint of SOB,
where he was initially hypotensive to the ___ by EMS, was given
1 L IVF with miprovement of blood pressures. Labs with Cr 2.01,
BNP 12,715 and negative troponin. Transferred here given he is
planned to have his pacer wire replaced. Admitted to cardiology
for monitoring and likley pacer revision while ___ house.
.
Patient reports his SOB occurs intermittently and describes it
as "hyperventilation." He reports the episodes come on randomly.
He endorses PND worsenign over the last week or so. Reports no
changes to his medications and adhereing to a low salt diet. Of
note he did call ___ today who reccomended he double his
lasix but he has not done so yet.
.
Was seen ___ the ED for similar episode ___ ___ and told this was
anxiety and to talk to his therapist about increasing his
anti-anxiety medications.

Past Medical History:
1. Chronic systolic heart failure and cardiomyopathy dating back

to ___ with LVEF as low as ___, currently 35-40%.
2. Pacemaker with ICD, no longer BiV pacing due to chest wall
stimulation.
3. Paranoid schizophrenia.
4. Depression.
5. Hypertension.
6. Hyperlipidemia.
7. Renal cancer with tumor extraction ___ ___.
8. GERD/ Barretts esophagus.
9. Complete teeth extraction.
10. Mild anemia.

Social History:
___
Family History:
Premature coronary artery disease
Paternal & Maternal grandfathers had heart dz

Physical Exam:
Admission:
VS- 98.3 118/81 100 24 98RA
Pulsus 8mmHg
GENERAL- WDWN gentleman ___ NAD. Oriented x3. Mood, affect
appropriate.
HEENT- NCAT. Sclera anicteric. PERRL, EOMI. Conjunctiva were
pink, no pallor or cyanosis of the oral mucosa. No xanthalesma.

NECK- Supple with no appreciable JVD however exam complicated by
body hapitub.
CARDIAC- distant HS. RRR. No MRG.
LUNGS- No chest wall deformities, scoliosis or kyphosis. Resp
were unlabored, no accessory muscle use. CTAB, no crackles,
wheezes or rhonchi.
ABDOMEN- Soft, NTND. No HSM or tenderness. Abd aorta not
enlarged by palpation. No abdominial bruits.
EXTREMITIES- No c/c/e. No femoral bruits. no edema

Discharge:
97.8 128/72 87 99 RA 81.4kg 149___
GENERAL- NAD. Oriented x3. Mood, affect appropriate.
HEENT- NCAT. Sclera anicteric. Conjunctiva were pink, no pallor
or cyanosis of the oral mucosa. No xanthalesma.
NECK- No JVD
CARDIAC- distant HS. RRR. No MRG.
LUNGS- No chest wall deformities, scoliosis or kyphosis. Resp
were unlabored, no accessory muscle use. CTAB, no crackles,
wheezes or rhonchi.
ABDOMEN- Soft, NTND. No HSM or tenderness. Abd aorta not
enlarged by palpation. No abdominial bruits.
EXTREMITIES- No c/c/e. No femoral bruits. no edema

Pertinent Results:
Admission:
___ 09:00PM BLOOD WBC-10.4 RBC-4.44* Hgb-13.6* Hct-39.9*
MCV-90 MCH-30.7 MCHC-34.2 RDW-15.3 Plt ___
___ 09:00PM BLOOD Neuts-61.1 ___ Monos-6.1 Eos-1.1
Baso-0.6
___ 09:00PM BLOOD ___ PTT-32.1 ___
___ 09:00PM BLOOD Glucose-77 UreaN-40* Creat-2.0* Na-143
K-4.1 Cl-107 HCO3-20* AnGap-20
___ 09:00PM BLOOD cTropnT-<0.01
___ 09:00PM BLOOD CK-MB-3 ___
___ 03:40PM BLOOD Calcium-9.3 Phos-5.3* Mg-2.3

Microbiology:
URINE CULTURE (Final ___:    NO GROWTH.

___ 7:00 pm SPUTUM      Source: Expectorated.

                            **FINAL REPORT ___

   GRAM STAIN (Final ___:
      <10 PMNs and <10 epithelial cells/100X field.
      1+    (<1 per 1000X FIELD):   GRAM POSITIVE ROD(S).
      1+    (<1 per 1000X FIELD):   GRAM NEGATIVE ROD(S).
      1+    (<1 per 1000X FIELD):   GRAM POSITIVE COCCI.
                                    ___ PAIRS  SINGLY.
      QUALITY OF SPECIMEN CANNOT BE ASSESSED.

   RESPIRATORY CULTURE (Final ___:
      SPARSE GROWTH Commensal Respiratory Flora.

Imaging:
___ CXR:
FINDINGS: The lungs are somewhat low ___ volume without focal
consolidation,
pleural effusion or pneumothorax.  The heart is stably enlarged
with 3 lead
pacemaker/defibrillator noted.  No pleural effusion or
pneumothorax is seen.
Bilateral lateral pleural thickening is noted, unchanged since
___.

IMPRESSION: Unchanged examination without acute intrathoracic
process.

___ Echo:
The left atrium is moderately dilated. The estimated right
atrial pressure is at least 15 mmHg. Left ventricular wall
thicknesses are normal. The left ventricular cavity is severely
dilated. There is severe global left ventricular hypokinesis
(LVEF = 10 %). The right ventricular free wall thickness is
normal. The right ventricular cavity is dilated with depressed
free wall contractility. The diameters of aorta at the sinus,
ascending and arch levels are normal. The aortic valve leaflets
(3) are mildly thickened. There is no aortic valve stenosis. No
aortic regurgitation is seen. The mitral valve leaflets are
mildly thickened. There is no mitral valve prolapse. Severe (4+)
mitral regurgitation is seen. Severe [4+] tricuspid
regurgitation is seen. There is at least moderate pulmonary
artery systolic hypertension. ___ the setting of at least
moderate to severe tricuspid regurgitation, the estimated
pulmonary artery systolic pressure may be underestimated due to
a very high right atrial pressure.] The end-diastolic pulmonic
regurgitation velocity is increased suggesting pulmonary artery
diastolic hypertension. There is no pericardial effusion. There
is an anterior space which most likely represents a prominent
fat pad.

Marked left ventricular mechanical dyssynchrony is present.
However, marked ventricular interaction with reverse Bernheim
phenomenon is also seen, due to marked right ventricular
pressure and volume overload.

Compared with the prior study (images reviewed) of ___,
both ventricles are even more dilated, and severe mitral and
tricuspid regurgitation are now present. Mechanical left
ventricular dyssynchrony remains evident.

___ Right Heart Cath:
COMMENTS:
1. Resting hemodynamics revealed elevated right and left heart
filling
pressures.  The RA mean pressure was 22 mmHg, mean PCW 31 mmHg.
The
cardiac index calculated using the Fick equation was 1.57
l/min/m2.

FINAL DIAGNOSIS:
1. Elevated right and left heart filling pressures.
2. Low cardiac index.

___ 10:17AM Echo:
The estimated right atrial pressure is at least 15 mmHg. Left
ventricular wall thicknesses are normal. The left ventricular
cavity is severely dilated. Overall left ventricular systolic
function is profoundly depressed (LVEF = 10%). Significant left
ventricular mechanical dyssynchrony is present (posterior wall
remains the site of latest activation). The right ventricular
free wall thickness is normal. The right ventricular cavity is
dilated with depressed free wall contractility. Moderate (2+)
mitral regurgitation is seen. Moderate [2+] tricuspid
regurgitation is seen. There is mild pulmonary artery systolic
hypertension. There is a trivial/physiologic pericardial
effusion.

Compared with the findings of the prior study (images reviewed)
of ___, the appearance of mitral and tricuspid
regurgitation is reduced. Marked left ventricular dyssynchrony
persists. Right ventricular function appears similar.

___ 3:34PM Echo:
The left ventricular cavity is severely dilated. Overall left
ventricular systolic function is severely depressed (LVEF = 15
%). [Due to acoustic shadowing, the severity of tricuspid
regurgitation may be significantly UNDERestimated.]

Compared with the findings of the prior study (images reviewed)
of ___, the overall left ventricular ejection
fraction is increased as a result of reduced mechanical
dyssynchrony

___ CXR:
CONCLUSION:
1.  There is no pneumothorax.
2.  Right-sided PICC line is still looped inside the subclavian
vein.
3.  Unchanged bibasilar consolidation.

___ CXR:
FINDINGS:  As compared to the previous radiograph, the gastric
distention has decreased.  There is unchanged evidence of low
lung volumes with areas of atelectasis at the lung bases.  The
ECG cables, pacemaker wires and right PICC line are constant.
Unchanged moderate cardiomegaly.  No new parenchymal opacities
___ the ventilated lung zones.  No pneumothorax.

___ 7:44AM CXR:
FINDINGS:  As compared to the previous radiograph, there is no
relevant
change.  Moderate cardiomegaly with moderate pulmonary edema.
The areas of
increased density at the right lung base are minimally
progressive.  No new
parenchymal opacities.  No pneumothorax.

___ 12:59PM CXR:
FINDINGS:  As compared to the previous image, there is minimally
improved
ventilation at both the left and right lung base.  Plate-like
atelectasis at the level of the left hilus.  Normal size of the
cardiac silhouette.  No
evidence of pneumothorax.

Discharge:
___ 06:40AM BLOOD WBC-12.6* RBC-4.89 Hgb-14.3 Hct-43.7
MCV-89 MCH-29.3 MCHC-32.8 RDW-15.4 Plt ___
___ 06:40AM BLOOD Plt ___
___ 06:40AM BLOOD Glucose-99 UreaN-78* Creat-1.8* Na-130*
K-3.7 Cl-84* HCO3-32 AnGap-18
___ 06:40AM BLOOD Calcium-9.6 Phos-4.4 Mg-2.7*

Brief Hospital Course:
Brief Course:
___ YOM with history of non-ischemic cardiomyopathy s/p Dual
Chamber ICD presenting with CC of intermittent SOB and
transferred from OSH out of concern for decompensated CHF.

Active Issues:
# Acute on chronic systolic CHF: EF 10% on echo ___. RHC
showing RA mean 22, PA mean 39, PCW mean 39, CO 3.16, CI 1.57,
suggesting elevated filling pressures and low cardiac output.
BNP is elevated to ___, no baseline. Exacerbation may be
secondary to ventricular dyssynchrony since the left ventricular
lead was shut off after it was noted to cause significant chest
wall stimulation. Patient was started on a milrinone drip ___
conjunction with lasix drip for optimization prior to BiV lead
manipulation. The patient underwent left thoracotomy with left
ventricular pacing wire placement on ___. He was
successfully extubated ___ the OR and transferred to the CVICU
with a left chest tube ___ place set to suction. Post-op CXR was
notable for no pneumothorax and a new LV lead. Post-op echo
notable for no pericardial effusion, improved dyssynchrony, EF
___ and no intracardiac thrombi. Milrinone and furosemide
drips were continued post procedure. On the morning for ___
the patient became hypotensive with SBPs ___ ___. He was
administered albumin with a transient increase ___ pressure to
SBP ___.  Milrinone and furosemide were stopped and
norepinephrine was started. A stat echocardiogram showed
significant left ventricular mechanical dyssynchrony and dilated
right ventricular cavity with depressed free wall contractility.
It was thought that the LV lead was not capturing.
Norepinephrine was stopped and dopamine started, with an
increase ___ UOP and improvement ___ blood pressure. The CCU was
consulted and the patient transferred. CVP prior to transfer was
12, and SvO2 61%. The patient denied any CP or dyspnea at the
time of transfer. Repeat CXR showed fluid ___ the right fissure
but improving atelectasis. Dopamine was discontinued on arrival
to the CCU per the heart failure team. The patient was
transiently placed back on milrinone and furosemide drips which
were discontinued and replaced by dobutamine and norepinephrine.
He was diuresed with intermittent boluses of furosemide,
furosemide drip and metolazone for a goal CVP ___. SBPs of
80-90s were tolerated. The patient required low dose
norepinephrine for pressure support during diuresis. The chest
tube was pulled by cardiac surgery on ___. Pt was started
on torsemide 60mg BID on ___ which was decreased to
torsemide 40mg daily on ___ when the patient was clinically
euvolemic. He was also started on isosorbide dinitrate and low
dose metoprolol. His isosorbide dinitrate was converted to
mononitrate prior to discharge.

# Acute on CKD: Baseline creatinine 1.5-2. Creatinine trended up
and peaked at 2.9, likely from cardio-renal syndrome. Creatinine
improved with milrinone and diuresis.

# Hyponatremia: Likely due to appropriate ADH secretion ___
setting of cardiorenal syndrome given high urine Na and
improvement with fluid restriction.

# Leukocytosis: No infectious symptoms. Urine culture negative.

# Anxiety: Hyperventilates when upset, responds well to calming.
Continued on alprazolam.

Inactive Issues:
# Paranoid schizophrenia: Continued on olanzapine.

# Right middle lobe atelectasis: Seen on CXR from ___, but now
appears denser. Radiology recommends follow up CT to rule out
post-obstuctive atelectasis.

Transitional Issues:
# Acute on chronic systolic CHF: patient started on metorpolol,
spironolactone, isosorbide, torsemide and should be followed for
response to therapy, side effects.

Medications on Admission:
The Preadmission Medication list is accurate and complete.
1. ALPRAZolam 0.5 mg PO BID:PRN anxiety
hold for rr<10 or oversedation
2. Atorvastatin 10 mg PO DAILY
3. Furosemide 40 mg PO DAILY
hold for sbp<100
4. Lisinopril 5 mg PO DAILY
hold for sbp<100
5. Metoprolol Succinate XL 100 mg PO DAILY
hold fro sbp<100 or hr<50
6. OLANZapine 5 mg PO QAM
7. OLANZapine 10 mg PO HS
8. Omeprazole 20 mg PO BID
9. Topiramate (Topamax) 25 mg PO BID
10. Aspirin 81 mg PO DAILY
11. Vitamin D 1000 UNIT PO DAILY
12. Fish Oil (Omega 3) 1200 mg PO BID


Discharge Medications:
1. ALPRAZolam 0.5 mg PO BID:PRN anxiety
hold for rr<10 or oversedation
2. Aspirin 81 mg PO DAILY
3. Atorvastatin 10 mg PO DAILY
4. OLANZapine 5 mg PO QAM
5. OLANZapine 10 mg PO HS
6. Omeprazole 20 mg PO BID
7. Topiramate (Topamax) 25 mg PO BID
8. Vitamin D 1000 UNIT PO DAILY
9. Fish Oil (Omega 3) 1200 mg PO BID
10. Metoprolol Succinate XL 12.5 mg PO DAILY
RX *metoprolol succinate 25 mg 0.5 (One half) tablet(s) by mouth
daily Disp #*30 Tablet Refills:*3
11. Isosorbide Mononitrate (Extended Release) 30 mg PO DAILY
RX *isosorbide mononitrate 30 mg 1 tablet(s) by mouth daily Disp
#*30 Tablet Refills:*3
12. Torsemide 40 mg PO DAILY
RX *torsemide 20 mg 2 tablet(s) by mouth daily Disp #*60 Tablet
Refills:*3
13. Spironolactone 12.5 mg PO DAILY
RX *spironolactone 25 mg 0.5 (One half) tablet(s) by mouth daily
Disp #*30 Tablet Refills:*3


Discharge Disposition:
Home With Service

Facility:
___

Discharge Diagnosis:
Primary diagnosis:
Acute on chronic systolic congestive heart failure


Discharge Condition:
Mental Status: Clear and coherent.
Level of Consciousness: Alert and interactive.
Activity Status: Ambulatory - Independent.


Discharge Instructions:
Dear Mr. ___,

It was a pleasure taking care of you at ___. You were admitted
with shortness of breath due to worsening heart failure. We gave
you medicine through your veins which helped to remove some of
the fluid from your body. You also had your pacemaker wire
repositioned which should help improve the function of your
heart.

Weigh yourself every morning, call MD if weight goes up more
than 3 lbs.

START
spironolactone
torsemide
isosorbide mononitrate

CHANGE
metoprolol succinate 100mg to 12.5mg

STOP
furosemide (replaced with torsemide)
lisinopril (this will be temporarily held to prevent your blood
pressure from dropping too low. You should talk to your
cardiologist about resuming this when you have left the
hospital)

Followup Instructions:
___

In [134]:
admissions = pd.read_csv('mimic/mimic-iv-clinical-database-demo-2.2/hosp/admissions.csv.gz')

In [136]:
admissions.admission_type

0                           URGENT
1                           URGENT
2                           URGENT
3                           URGENT
4                           URGENT
                  ...
270    SURGICAL SAME DAY ADMISSION
271    SURGICAL SAME DAY ADMISSION
272    SURGICAL SAME DAY ADMISSION
273    SURGICAL SAME DAY ADMISSION
274    SURGICAL SAME DAY ADMISSION
Name: admission_type, Length: 275, dtype: object

In [141]:
print(dc.text[0])

Name:  ___                     Unit No:   ___

Admission Date:  ___              Discharge Date:   ___

Date of Birth:  ___             Sex:   F

Service: MEDICINE

Allergies:
No Known Allergies / Adverse Drug Reactions

Attending: ___

Chief Complaint:
Worsening ABD distension and pain

Major Surgical or Invasive Procedure:
Paracentesis


History of Present Illness:
___ HCV cirrhosis c/b ascites, hiv on ART, h/o IVDU, COPD,
bioplar, PTSD, presented from OSH ED with worsening abd
distension over past week.
Pt reports self-discontinuing lasix and spirnolactone ___ weeks
ago, because she feels like "they don't do anything" and that
she "doesn't want to put more chemicals in her." She does not
follow Na-restricted diets. In the past week, she notes that she
has been having worsening abd distension and discomfort. She
denies ___ edema, or SOB, or orthopnea. She denies f/c/n/v, d/c,
dysuria. She had food poisoning a week ago from eating stale
cake (n/v 20 min after food ingestion), which resolved the same
day. She denies other recent illness or sick contacts. She notes
that she has been noticing gum bleeding while brushing her teeth
in recent weeks. she denies easy bruising, melena, BRBPR,
hemetesis, hemoptysis, or hematuria.
Because of her abd pain, she went to OSH ED and was transferred
to ___ for further care. Per ED report, pt has brief period of
confusion - she did not recall the ultrasound or bloodwork at
osh. She denies recent drug use or alcohol use. She denies
feeling confused, but reports that she is forgetful at times.
In the ED, initial vitals were 98.4 70 106/63 16 97%RA
Labs notable for ALT/AST/AP ___ ___: ___,
Tbili1.6, WBC 5K, platelet 77, INR 1.6


Past Medical History:
1. HCV Cirrhosis
2. No history of abnormal Pap smears.
3. She had calcification in her breast, which was removed
previously and per patient not, it was benign.
4. For HIV disease, she is being followed by Dr. ___ Dr.
___.
5. COPD
6. Past history of smoking.
7. She also had a skin lesion, which was biopsied and showed
skin cancer per patient report and is scheduled for a complete
removal of the skin lesion in ___ of this year.
8. She also had another lesion in her forehead with purple
discoloration. It was biopsied to exclude the possibility of
___'s sarcoma, the results is pending.
9. A 15 mm hypoechoic lesion on her ultrasound on ___
and is being monitored by an MRI.
10. History of dysplasia of anus in ___.
11. Bipolar affective disorder, currently manic, mild, and PTSD.

12. History of cocaine and heroin use.


Social History:
___
Family History:
She a total of five siblings, but she is not
talking to most of them. She only has one brother that she is in

touch with and lives in ___. She is not aware of any
known GI or liver disease in her family.
Her last alcohol consumption was one drink two months ago. No
regular alcohol consumption. Last drug use ___ years ago. She
quit smoking a couple of years ago.


Physical Exam:
VS: 98.1 107/61 78 18 97RA
General: in NAD
HEENT: CTAB, anicteric sclera, OP clear
Neck: supple, no LAD
CV: RRR,S1S2, no m/r/g
Lungs: CTAb, prolonged expiratory phase, no w/r/r
Abdomen: distended, mild diffuse tenderness, +flank dullness,
cannot percuss liver/spleen edge ___ distension
GU: no foley
Ext: wwp, no c/e/e, + clubbing
Neuro: AAO3, converse normally, able to recall 3 times after 5
minutes, CN II-XII intact

Discharge:

PHYSICAL EXAMINATION:
VS: 98 105/70 95
General: in NAD
HEENT: anicteric sclera, OP clear
Neck: supple, no LAD
CV: RRR,S1S2, no m/r/g
Lungs: CTAb, prolonged expiratory phase, no w/r/r
Abdomen: distended but improved, TTP in RUQ,
GU: no foley
Ext: wwp, no c/e/e, + clubbing
Neuro: AAO3,  CN II-XII intact


Pertinent Results:
___ 10:25PM   GLUCOSE-109* UREA N-25* CREAT-0.3* SODIUM-138
POTASSIUM-3.4 CHLORIDE-105 TOTAL CO2-27 ANION GAP-9
___ 10:25PM   estGFR-Using this
___ 10:25PM   ALT(SGPT)-100* AST(SGOT)-114* ALK PHOS-114*
TOT BILI-1.6*
___ 10:25PM   LIPASE-77*
___ 10:25PM   ALBUMIN-3.3*
___ 10:25PM   WBC-5.0# RBC-4.29 HGB-14.3 HCT-42.6 MCV-99*
MCH-33.3* MCHC-33.5 RDW-15.7*
___ 10:25PM   NEUTS-70.3* LYMPHS-16.5* MONOS-8.1 EOS-4.2*
BASOS-0.8
___ 10:25PM   PLT COUNT-71*
___ 10:25PM   ___ PTT-30.9 ___
___ 10:25PM   ___
.

CXR: No acute cardiopulmonary process.
U/S:
1. Nodular appearance of the liver compatible with cirrhosis.
Signs of portal
hypertension including small amount of ascites and splenomegaly.

2. Cholelithiasis.
3. Patent portal veins with normal hepatopetal flow.
Diagnostic para attempted in the ED, unsuccessful.
On the floor, pt c/o abd distension and discomfort.

Brief Hospital Course:
___ HCV cirrhosis c/b ascites, hiv on ART, h/o IVDU, COPD,
bioplar, PTSD, presented from OSH ED with worsening abd
distension over past week and confusion.

# Ascites - p/w worsening abd distension and discomfort for last
week. likely ___ portal HTN given underlying liver disease,
though no ascitic fluid available on night of admission. No
signs of heart failure noted on exam. This was ___ to med
non-compliance and lack of diet restriction. SBP negative
diuretics:
> Furosemide 40 mg PO DAILY
> Spironolactone 50 mg PO DAILY, chosen over the usual 100mg
dose d/t K+ of 4.5.
 CXR was wnl, UA negative, Urine culture blood culture negative.

Pt was losing excess fluid appropriately with stable lytes on
the above regimen. Pt was scheduled with current PCP for
___ check upon discharge.
Pt was scheduled for new PCP with Dr. ___ at ___ and
follow up in Liver clinic to schedule outpatient screening EGD
and ___.



Medications on Admission:
The Preadmission Medication list is accurate and complete.
1. Furosemide 20 mg PO DAILY
2. Spironolactone 50 mg PO DAILY
3. Albuterol Inhaler 2 PUFF IH Q4H:PRN wheezing, SOB
4. Raltegravir 400 mg PO BID
5. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY
6. Nicotine Patch 14 mg TD DAILY
7. Ipratropium Bromide Neb 1 NEB IH Q6H SOB


Discharge Medications:
1. Albuterol Inhaler 2 PUFF IH Q4H:PRN wheezing, SOB
2. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY
3. Furosemide 40 mg PO DAILY
RX *furosemide 40 mg 1 tablet(s) by mouth Daily Disp #*30 Tablet
Refills:*3
4. Ipratropium Bromide Neb 1 NEB IH Q6H SOB
5. Nicotine Patch 14 mg TD DAILY
6. Raltegravir 400 mg PO BID
7. Spironolactone 50 mg PO DAILY
8. Acetaminophen 500 mg PO Q6H:PRN pain


Discharge Disposition:
Home

Discharge Diagnosis:
Ascites from Portal HTN


Discharge Condition:
Mental Status: Clear and coherent.
Level of Consciousness: Alert and interactive.
Activity Status: Ambulatory - Independent.


Discharge Instructions:
Dear Ms. ___,
It was a pleasure taking care of you! You came to us with
stomach pain and worsening distension. While you were here we
did a paracentesis to remove 1.5L of fluid from your belly. We
also placed you on you 40 mg of Lasix and 50 mg of Aldactone to
help you urinate the excess fluid still in your belly. As we
discussed, everyone has a different dose of lasix required to
make them urinate and it's likely that you weren't taking a high
enough dose. Please take these medications daily to keep excess
fluid off and eat a low salt diet. You will follow up with Dr.
___ in liver clinic and from there have your colonoscopy
and EGD scheduled. Of course, we are always here if you need us.
We wish you all the best!
Your ___ Team.

Followup Instructions:
___

In [ ]:
dc_details = pd.read_csv('mimic/mimic-iv-notes-2.2/note/discharge_detail.csv.gz')

In [6]:
hosp_adm = pd.read_csv('mimic/mimic-iv-3.1/hosp/admissions.csv.gz')

In [ ]:
icd = pd.read_csv('mimic/mimic-iv-3.1/hosp/d_icd_diagnoses.csv.gz')

In [ ]:
set([c for c in ddx.icd_title if 'lung' in c.lower() and 'neoplasm' in c.lower()])

In [342]:
rel_codes = icd[icd.long_title.isin([t for t in icd.long_title if ('lung' in t.lower()) and ('neoplasm' in t.lower())] )].icd_code
rel_codes = ['1623',
 '1624',
 '1625',
 '1628',
 '1629',
 '2123',
 '2357',
 'C34',
 'C341',
 'C3410',
 'C3411',
 'C3412',
 'C342',
 'C343',
 'C3430',
 'C3431',
 'C3432',
 'C348',
 'C3480',
 'C3481',
 'C3482',
 'C349',
 'C3490',
 'C3491',
 'C3492',
 'D143',
 'D1430',
 'D1431',
 'D1432',
 'D381',
 'V1011',
 'Z851',
 'Z8511',
 'Z85118']

In [9]:
hdx = pd.read_csv('mimic/mimic-iv-3.1/hosp/diagnoses_icd.csv.gz')

In [10]:
hdx

         subject_id   hadm_id  seq_num icd_code  icd_version
0          10000032  22595853        1     5723            9
1          10000032  22595853        2    78959            9
2          10000032  22595853        3     5715            9
3          10000032  22595853        4    07070            9
4          10000032  22595853        5      496            9
...             ...       ...      ...      ...          ...
6364483    19999987  23865745        7    41401            9
6364484    19999987  23865745        8    78039            9
6364485    19999987  23865745        9     0413            9
6364486    19999987  23865745       10    36846            9
6364487    19999987  23865745       11     7810            9

[6364488 rows x 5 columns]

In [333]:
h = hdx[hdx.icd_code.isin(rel_codes)].subject_id.value_counts()

In [334]:
_icd = icd.set_index(['icd_version', 'icd_code'])

In [ ]:
_hdx = hdx[hdx.subject_id.isin(cs3)]
_hdx = _hdx.join(_icd, on=['icd_version', 'icd_code'])
_hdx = _hdx.join(hosp_adm[['hadm_id', 'admittime']].set_index('hadm_id'), on='hadm_id')

In [371]:
pd.read_csv('mimic/mimic-iv-3.1/hosp/patients.csv.gz')

,subject_id,gender,anchor_age,anchor_year,anchor_year_group,dod
0,10000032,F,52,2180,2014 - 2016,2180-09-09
1,10000048,F,23,2126,2008 - 2010,NaN
2,10000058,F,33,2168,2020 - 2022,NaN
3,10000068,F,19,2160,2008 - 2010,NaN
4,10000084,M,72,2160,2017 - 2019,2161-02-13
...,...,...,...,...,...,...
364622,19999828,F,46,2147,2017 - 2019,NaN
364623,19999829,F,28,2186,2008 - 2010,NaN
364624,19999840,M,58,2164,2008 - 2010,2164-09-17
364625,19999914,F,49,2158,2017 - 2019,NaN
364626,19999987,F,57,2145,2011 - 2013,NaN

In [471]:
SUBJECT_ID = 10025612
dc[dc.subject_id == SUBJECT_ID].sort_values('charttime')
print(dc[dc.subject_id == SUBJECT_ID].sort_values('charttime').text[825])

Name:  ___                Unit No:   ___

Admission Date:  ___              Discharge Date:   ___

Date of Birth:  ___             Sex:   M

Service: CARDIOTHORACIC

Allergies:
No Known Allergies / Adverse Drug Reactions

Attending: ___.

Chief Complaint:
Recurrent lung cancer

Major Surgical or Invasive Procedure:
Cervical mediastinoscopy, redo left thoracotomy, completion left
pneumonectomy, mediastinal lymph node dissection, bronchoscopy
with bronchoalveolar lavage, pericardial fat pad buttress -
___

Left thoracotomy with evacuation of hemothorax and ligation
intercostal artery, excision of pericardial fat pad and
placement of a pleural flap - ___


History of Present Illness:
Mr. ___ is an ___ year old male from ___ who presented
for a second opinion of recurrent left lung cancer. He had
similar symptoms in ___ and had a left lower lobe nodule
requiring surgery with ultimately a completion left lower
lobectomy with post op chemotherapy. He did well and was
followed closely but symptoms of a cough recurred in ___. a
left upper lobe mass was
discovered for which he underwent a posterior segmentectomy
(pT1bNxMx). He recovered well and had been feeling well until a
dry cough recurred 3 months ago. A chest CT showed a new
retrohilar mass and this was PET positive.
Other than the cough he feels well. He's very active in
___ work in his ___ complex and takes care of his
wife who has ___ isease. He admits to slight DOE if he
over exerts but generally has no problems. He has some general
arthritic complaints but no specific bone pain.  He denies
hemoptysis, recent weight loss or shortness of breath.

Past Medical History:
PMH: Hypothyroid, BPV, Macular degeneration, Right breast
cancer, recurrent left lung cancer

PSH: Right breast lumpectomy ___ ___iff ductal Ca with
post op Tamoxifen, Left lower lobe wedge resection with
completion left lower lobectomy ___ for mod diff adeno ca, all
nodes negative. Post op chemo; Posterior segmentectomy of left
upper lobe ___ for adeno ca (mixed papillary/micropapillary
45%, acinar 45%, solid 10%) pT1bNxMx; ___ x 2 (last ___ w/
mesh); S/P Right cataract excision w/ ___

Social History:
___
Family History:
Mother breast ___
Father  ___ No Ca
Offspring 3 healthy sons

Physical ___:
Physical exam on discharge:
98.2  97.6  74  107/55  18  97%RA
Gen - AAO x 3 NAD
CV - RRR +S1/S2 no murmurs/rubs/gallops
P - CTA on right side, absence of breath sounds on left (to be
expected s/p completion pneumonectomy)
Abd - soft/nontender/nondistended
Inc - clean/dry/intact, no erythema/drainage/induration
Ext - no edema/cyanosis/clubbing

Pertinent Results:
___ 06:55AM BLOOD WBC-8.3 RBC-4.39* Hgb-13.4* Hct-40.4
MCV-92 MCH-30.5 MCHC-33.2 RDW-14.8 Plt ___
___ 06:55AM BLOOD Plt ___
___ 05:05AM BLOOD ___ PTT-28.1 ___
___ 06:55AM BLOOD Glucose-82 UreaN-16 Creat-0.8 Na-139
K-4.2 Cl-102 HCO3-27 AnGap-14
___ 06:55AM BLOOD Calcium-8.4 Phos-3.3 Mg-1.9

CHEST X-RAY ___
As compared to the previous radiograph, there is no relevant
change
in appearance of the post-pneumonectomy left hemithorax.  The
multiple
air-fluid levels as well as the amount of air in the soft
tissues is
relatively constant.  The clips also in constant position.
Unchanged normal appearance of the right lung.


Brief Hospital Course:
Mr ___ was admitted to the ICU after his operation. His
initial ___ was complicated by return to OR for hemothorax
evacuation. After this, he returned to the ICU, but was able to
be transferred to the floor on POD ___. His post-operative
course may be described by systems as below:

Neuro: He was intubated/sedated after each of his operations.
Once appropriate, he was extubated without issue. He was
initially given IV pain medications for pain control, and
transitioned to oral medications once appropriate. He tolerated
this well.

CV: Required phenylephrine for blood pressure after first
operation; this was successfully weaned. He once more required
pressors again after second operation, also weaned without
issue. After that, he remained hemodynamically stable throughout
his stay. Due to the aforementioned times of hypotension and
pressor requirement, Cardiology was consulted and MI was ruled
out by means of serial EKGs and troponin checks. The patient was
eventually diuresed gently due to his multiple fluid
resuscitations with increased risk for CHF. He tolerated this
well. He had no arrhythmias post op but was started on, and will
continue on Diltiazem for afib prophylaxis for an additional 3
weeks.

Pulm: He was extubated when appropriate post-operatively. On
POD1, his chest tube output had decreased, then suddenly put out
240 cc of serosanguinous output, then improved. The chest tube
was removed. However, overnight POD1-2, there was concern for
hemothorax on CXR and drop in Hct. A chest tube was placed and
he returned to the operating room for an exploratory thoracotomy
and evacuation of hematoma. Afterwards, he was once more
extubated when appropriate. The chest tube was removed on POD
___ and repeat CXR showed no PTX. His weight was elevated, so
diuresis was begun with furosemide as mentioned above, till he
returned to his pre-operative dry weight.

GI: He had emesis after each operation, thought to be likely due
to anesthesia effect. Eventually, however, he tolerated a
regular diet, though did have a decreased appetite. He was
started on Marinol to assist with this. He had normal bowel
movements throughout his stay.

GU: He initially had a foley catheter in place for close urine
output monitoring. When appropriate, this was removed, and he
voided successfully without issue.

Endo: no active issues

Heme: Aforementioned hematocrit drop required takeback to OR.
Hct monitored closely after that, and remained stable
throughout.

ID: He received ___ antibiotics for prophylaxis.

The patient was doing well and discharged on ___. He will
stay locally for approximately one week and then follow up with
Dr. ___ prior to returning to ___.

Medications on Admission:
The Preadmission Medication list is accurate and complete.
1. Meclizine 12.5 mg PO DAILY:PRN dizziness
2. Levothyroxine Sodium 25 mcg PO DAILY


Discharge Medications:
1. Acetaminophen 1000 mg PO Q8H
2. Levothyroxine Sodium 25 mcg PO DAILY
3. Meclizine 12.5 mg PO DAILY
4. Docusate Sodium 100 mg PO BID
RX *docusate sodium [Colace] 100 mg 1 capsule(s) by mouth twice
a day Disp #*20 Capsule Refills:*0
5. OxycoDONE (Immediate Release)  ___ mg PO Q4H:PRN pain
use for pain unrelieved by Tramadol
RX *oxycodone 5 mg ___ tablet(s) by mouth every four (4) hours
Disp #*50 Tablet Refills:*0
6. Senna 1 TAB PO BID:PRN constipation
7. Diltiazem 30 mg PO TID Duration: 3 Weeks
RX *diltiazem HCl [Cardizem] 30 mg 1 tablet(s) by mouth three
times a day Disp #*63 Tablet Refills:*0
8. TraMADOL (Ultram) 25 mg PO QID
RX *tramadol 50 mg 0.5 (One half) tablet(s) by mouth four times
a day Disp #*20 Tablet Refills:*0
9. Assistive device

Wheelchair

Dx: S/P left pneumonectomy
10. Dronabinol 2.5 mg PO BID
RX *dronabinol 2.5 mg 1 capsule(s) by mouth twice a day Disp
#*20 Capsule Refills:*0


Discharge Disposition:
Home With Service

Facility:
___

Discharge Diagnosis:
Recurrent lung cancer
Hemothorax
Acute blood loss anemia


Discharge Condition:
Mental Status: Clear and coherent.
Level of Consciousness: Alert and interactive.
Activity Status: Ambulatory - Independent.


Discharge Instructions:
Dear Mr. ___,

You were admitted to ___ Thoracic Surgical Service after
your operation. You have done well in the hospital, and are
prepared to complete your recovery outside the hospital, with
the following instructions:

* Continue to use your incentive spirometer 10 times an hour
while awake.
* Check your incisions daily and report any increased redness or
drainage.   Cover the area with a gauze pad if it is draining.
* Check your incisions daily, no dressings are needed as long as
they remain dry.
* You will continue to need pain medication once you are home
but you can wean it over a few weeks as the discomfort resolves.
 Make sure that you have regular bowel movements while on
narcotic pain medications as they are constipating which can
cause more problems.  Use a stool softener or gentle laxative to
stay regular.
* No driving while taking narcotic pain medication.
* Take Tylenol  in between your narcotic.
* Continue to stay well hydrated and eat well to heal your
incisions
* Shower daily. Wash incision with mild soap & water, rinse, pat
dry
* No tub bathing, swimming or hot tubs until incision healed
* No lotions or creams to incision site
* Walk ___ times a day and gradually increase your activity as
you can tolerate.

* We have started you on two new medications called Diltiazem
and Dronabinol - please take these as prescribed. When you see
Dr. ___ in clinic, he will determine if you need to keep
taking these.
* You have been set up with ___ visiting nursing, as well as a
wheelchair to help you get around. We do encourage you keep
trying to ambulate yourself as much as possible.

Call Dr. ___ ___ if you experience:
-Fevers > 101 or chills
-Increased shortness of breath, chest pain or any other symptoms
that concern you.

Followup Instructions:
___

In [475]:
i = 11
_hdx[_hdx.subject_id==_hdx.subject_id.unique()[i]].sort_values(['admittime', 'seq_num']).head(50) #.query('hadm_id==21476780')

,subject_id,hadm_id,seq_num,icd_code,icd_version,long_title,admittime
33698,10052550,27708578,1,51631,9,Idiopathic pulmonary fibrosis,2174-11-08 13:33:00
33699,10052550,27708578,2,42831,9,Acute diastolic heart failure,2174-11-08 13:33:00
33700,10052550,27708578,3,5849,9,"Acute kidney failure, unspecified",2174-11-08 13:33:00
33701,10052550,27708578,4,51289,9,Other pneumothorax,2174-11-08 13:33:00
33702,10052550,27708578,5,25002,9,Diabetes mellitus without mention of complicat...,2174-11-08 13:33:00
33703,10052550,27708578,6,7140,9,Rheumatoid arthritis,2174-11-08 13:33:00
33704,10052550,27708578,7,79902,9,Hypoxemia,2174-11-08 13:33:00
33705,10052550,27708578,8,99881,9,Emphysema (subcutaneous) (surgical) resulting ...,2174-11-08 13:33:00
33706,10052550,27708578,9,E8798,9,Other specified procedures as the cause of abn...,2174-11-08 13:33:00
33707,10052550,27708578,10,E9443,9,Saluretics causing adverse effects in therapeu...,2174-11-08 13:33:00
33708,10052550,27708578,11,E9331,9,Antineoplastic and immunosuppressive drugs cau...,2174-11-08 13:33:00
33709,10052550,27708578,12,2767,9,Hyperpotassemia,2174-11-08 13:33:00
33710,10052550,27708578,13,4019,9,Unspecified essential hypertension,2174-11-08 13:33:00
33711,10052550,27708578,14,2859,9,"Anemia, unspecified",2174-11-08 13:33:00
33712,10052550,27708578,15,V1582,9,Personal history of tobacco use,2174-11-08 13:33:00
33713,10052550,27708578,16,V1011,9,Personal history of malignant neoplasm of bron...,2174-11-08 13:33:00
33714,10052550,27708578,17,V5867,9,Long-term (current) use of insulin,2174-11-08 13:33:00
33715,10052550,27708578,18,53081,9,Esophageal reflux,2174-11-08 13:33:00
33716,10052550,27708578,19,V161,9,Family history of malignant neoplasm of trache...,2174-11-08 13:33:00
33717,10052550,27708578,20,2721,9,Pure hyperglyceridemia,2174-11-08 13:33:00
33718,10052550,27708578,21,V160,9,Family history of malignant neoplasm of gastro...,2174-11-08 13:33:00

In [11]:
hdx

         subject_id   hadm_id  seq_num icd_code  icd_version
0          10000032  22595853        1     5723            9
1          10000032  22595853        2    78959            9
2          10000032  22595853        3     5715            9
3          10000032  22595853        4    07070            9
4          10000032  22595853        5      496            9
...             ...       ...      ...      ...          ...
6364483    19999987  23865745        7    41401            9
6364484    19999987  23865745        8    78039            9
6364485    19999987  23865745        9     0413            9
6364486    19999987  23865745       10    36846            9
6364487    19999987  23865745       11     7810            9

[6364488 rows x 5 columns]

In [493]:
print(dc.text[2])

Name:  ___                     Unit No:   ___

Admission Date:  ___              Discharge Date:   ___

Date of Birth:  ___             Sex:   F

Service: MEDICINE

Allergies:
Percocet / Vicodin

Attending: ___

Chief Complaint:
altered mental status

Major Surgical or Invasive Procedure:
none

History of Present Illness:
Mrs. ___ is a ___ female with HIV on HAART, COPD, HCV
cirrhosis complicated by ascites and hepatic encephalopathy who
initially presented to the ED yesterday with hypotension after a
paracentesis.
The patient has had accelerated decompensation of her cirrhosis
recently with worsening ascites, and she is maintained on twice
weekly paracentesis. She was at her regular session yesterday
when she had hypotension to SBP ___ and felt lightheadedness.
Per the patient, that's when her memory started to get fuzzy.
She does not have much recollection of what happened since then.
Her outpatient hepatologist saw her and recommended that she go
to the ED. In the ED, she was evaluated and deemed to have
stable blood pressure. She was discharged home. At home, she had
worsening mental status with her daughter getting concerned, and
she returned to the ED.
In the ED, initial vitals were 98.7 77 96/50 16 98% RA. The
patient was only oriented to person. Her labs were notable for
Na 126, K 6.7, Cr 0.7 (baseline 0.4), ALT 153, AST 275, TBili
1.9, Lip 66, INR 1.5. Initial EKG showed sinus rhythm with
peaked T waves. Her head CT was negative for any acute
processes. She received ceftriaxone 2gm x1, regular insulin 10U,
calcium gluconate 1g, lactulose 30 mL x2, and 25g 5% albumin.
On transfer, vitals were 99.0 93 84/40 16 95% NC. On arrival to
the MICU, patient was more alert and conversant. She has no
abdominal pain, nausea, vomiting, chest pain, or difficulty
breathing. She has a chronic cough that is not much changed. She
has not had any fever or chills. She reports taking all of her
medications except for lactulose, which she thinks taste
disgusting.

Past Medical History:
- HCV Cirrhosis: genotype 3a
- HIV: on HAART, ___ CD4 count 173, ___ HIV viral load
undetectable
- COPD: ___ PFT showed FVC 1.95 (65%), FEV1 0.88 (37%),
FEFmax 2.00 (33%)
- Bipolar Affective Disorder
- PTSD
- Hx of cocaine and heroin abuse
- Hx of skin cancer per patient report

Social History:
___
Family History:
She a total of five siblings, but she is not  talking to most of
them. She only has one brother that she is in  touch with and
lives in ___. She is not aware of any known GI or liver
disease in her family.

Physical Exam:
ADMISSION PHYSICAL EXAM:
Vitals T: 98.7 BP: 84/48 P: 91 R: 24 O2: 98% NC on 2L
GENERAL: Alert, oriented, no acute distress
LUNGS: Decreased air movement on both sides, scattered
expiratory wheezes
CV: Regular rate and rhythm, normal S1 S2, no murmurs, rubs,
gallops
ABD: Soft, non-tender, distended, flank dullness bilaterally,
bowel sounds present
EXT: Warm, well perfused, 2+ pulses, no cyanosis or edema

DISCHARGE PHYSICAL EXAM:
Vitals- Tm 99.5, Tc 98.7, ___ 79-96/43-58 20 95% on 3L NC,
7BM.
General- Cachectic-appearing woman, alert, oriented, no acute
distress
HEENT- Sclera anicteric, MMM, oropharynx clear, poor dentition
with partial dentures
Neck- supple, JVP not elevated, no LAD
Lungs- Clear to auscultation bilaterally, no wheezes, rales,
ronchi
CV- Regular rate and rhythm, normal S1 + S2, no murmurs, rubs,
gallops
Abdomen- Mildly distended and firm, non-tender, bowel sounds
present, no rebound tenderness or guarding
GU- no foley
Ext- warm, well perfused, 2+ pulses, no clubbing, cyanosis or
edema
Neuro- AOx3, No asterixis.

Pertinent Results:
ADMISSION LABS:
=================
___ 06:39AM BLOOD WBC-6.9 RBC-3.98* Hgb-14.1 Hct-41.1
MCV-103* MCH-35.4* MCHC-34.3 RDW-15.8* Plt ___
___ 06:39AM BLOOD Neuts-72.7* Lymphs-14.7* Monos-9.8
Eos-2.5 Baso-0.3
___ 06:39AM BLOOD ___ PTT-32.4 ___
___ 06:39AM BLOOD Glucose-102* UreaN-49* Creat-0.7 Na-126*
K-6.7* Cl-95* HCO3-25 AnGap-13
___ 06:39AM BLOOD ALT-153* AST-275* AlkPhos-114*
TotBili-1.9*
___ 06:39AM BLOOD Albumin-3.6

IMAGING/STUDIES:
================
___ CT HEAD:
No evidence of acute intracranial process.
The left zygomatic arch deformity is probably chronic as there
is no
associated soft tissue swelling.

___ CXR:
No acute intrathoracic process.

DISCHARGE LABS:
===============
___ 04:45AM BLOOD WBC-4.8 RBC-3.15* Hgb-11.2* Hct-32.1*
MCV-102* MCH-35.4* MCHC-34.8 RDW-15.8* Plt Ct-95*
___ 04:45AM BLOOD ___ PTT-37.6* ___
___ 04:45AM BLOOD Glucose-121* UreaN-35* Creat-0.4 Na-130*
K-5.2* Cl-97 HCO3-27 AnGap-11
___ 04:45AM BLOOD ALT-96* AST-168* AlkPhos-69 TotBili-1.7*
___ 04:45AM BLOOD Calcium-8.6 Phos-2.4* Mg-2.___ w/ HIV on HAART, COPD on 3L home O2, HCV cirrhosis
decompensated (ascites requiring biweekly therapeutic
paracenteses, hepatic encephalopathy; not on transplant list ___
comorbidities) w/ AMS, hypotension, ___, and hyperkalemia.
Altered mental status improved with lactulose. Hypotension was
felt to be due to fluid shifts from paracentesis on the day
prior to admission as well as low PO intake in the setting of
AMS. Hypotension and ___ resolved with IV albumin. Hyperkalemia
resolved with insulin and kayexalate.

# Hypotension: Patient presented with SBP in ___ and improved
with albumin in the ED to ___. It was felt to be due to
fluid shifts from paracentesis on ___, as well as likely
hypovolemia given AMS and decreased PO intake. No concern for
bleeding or sepsis with baseline CBC and lack of fever. She
continued to received IV albumin during her hospital course,
with which her SBP improved to ___ and patient remained
asymptomatic.

# Hyperkalemia: Patient presented with K 6.7 with EKG changes.
Given low Na, likely the result of low effective arterial volume
leading to poor K excretion, with likely exacerbation from ___.
AM cortisol was normal. K improved with insulin and kayexalate
and K was 5.2 on day of discharge. Bactrim was held during
hospital course.

# ___: Patient presented with Cr 0.7 from baseline Cr is
0.3-0.4. It was felt to be likely due to volume shift from her
paracentesis on the day prior to admission as well as now low
effective arterial volume, likely ___ poor PO intake ___ AMS. Cr
improved to 0.4 with albumin administration. Furosemide and
Bactrim were held during hospital course.

#GOC: The ___ son (HCP) met with Dr. ___
outpatient hepatologist) during ___ hospital course. They
discussed that the patient is not a transplant candidate
givenevere underlying lung disease (FEV1 ~0.8), hypoxia, RV
dilation and very low BMI. A more conservative approach was
recommended and the patient was transitioned to DNR/DNI. The
patient agreed with this plan. She was treated with the goal of
treating any any correctable issues. Social work met with the
patient prior to discharge. The patient was interested in
following up with palliative care, for which an outpatient
referral was made.

# Altered Mental Status: Patient presented with confusion that
was most likely secondary to hepatic encephalopathy. Based on
outpatient records, patient has had steady decline in
decompensated cirrhosis and mental status. No signs of infection
and head CT was negative as well. Mental status improved with
lactulose in the ED and patient reports that she has not been
taking lactulose regularly at home. Patient was also continued
on rifaximin.

# HCV Cirrhosis: Genotype 3a. Patient is decompensated with
increasing ascites and worsening hepatic encephalopathy. She is
dependent on twice weekly paracentesis. Spironolactone was
recently stopped due to hyperkalemia. Patient is not a
transplant candidate given her comorbidities COPD per outpatient
hepatologist. The patient would like to continue biweekly
paracenteses as an outpatient.

# HIV: Most recent CD4 count 173 on ___. HIV viral load on
___ was undetectable. She was continued on her home regimen
of raltegravir, emtricitabine, and tenofovir. Bactrim
prophylaxis was held during admission because of hyperkalemia.


# COPD: Patient on 3L NC at home. She was continued on her home
regimen.

TRANSITIONAL ISSUES:
-Follow up with Palliative Care as outpatient
-Bactrim prophylaxis (HIV+) was held during hospital course due
to ___. Consider restarting as outpatient.
-Furosemide was held due to ___, consider restarting as
outpatient
-Follow up with hepatology
-Continue biweekly therapeurtic paracenteses
-Code status: DNR/DNI

Medications on Admission:
The Preadmission Medication list is accurate and complete.
1. Lactulose 15 mL PO TID
2. Tiotropium Bromide 1 CAP IH DAILY
3. Raltegravir 400 mg PO BID
4. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY
5. Furosemide 40 mg PO DAILY
6. TraMADOL (Ultram) 50 mg PO Q8H:PRN Pain
7. Fluticasone Propionate 110mcg 1 PUFF IH BID
8. Calcium Carbonate 500 mg PO BID
9. Rifaximin 550 mg PO BID
10. albuterol sulfate 90 mcg/actuation inhalation Q6H:PRN
Wheezing
11. Sulfameth/Trimethoprim DS 1 TAB PO DAILY


Discharge Medications:
1. Calcium Carbonate 500 mg PO BID
2. Emtricitabine-Tenofovir (Truvada) 1 TAB PO DAILY
3. Fluticasone Propionate 110mcg 1 PUFF IH BID
4. Lactulose 30 mL PO TID
5. Raltegravir 400 mg PO BID
6. Rifaximin 550 mg PO BID
7. TraMADOL (Ultram) ___ mg PO Q6H:PRN pain
8. albuterol sulfate 90 mcg/actuation inhalation Q6H:PRN
Wheezing
9. Tiotropium Bromide 1 CAP IH DAILY


Discharge Disposition:
Home

Discharge Diagnosis:
Primary:
Hypotension
Hyperkalemia
Acute Kidney Injury

Secondary:
HIV
Cirrhosis
COPD

Discharge Condition:
Mental Status: Clear and coherent.
Level of Consciousness: Alert and interactive.
Activity Status: Ambulatory - Independent.

Discharge Instructions:
Dear Ms. ___,

You were admitted to ___ because of confusion, low blood
pressure, and a high potassium value. Your confusion improved
with lactulose. Your blood pressure improved with extra fluids
and your potassium improved as well. You also had small degree
of kidney injury when you came to the hospital, and this also
improved with fluids. While you were here, you discussed
changing your goals of care to focusing on symptom management
and treatment of reversible processes, such as an infection.
While you were in the hospital, you were seen by one of our
social workers. You will also follow up with Palliative Care in
their clinic and will continue to have therapeutic paracenteses.

It has been a pleasure taking care of you and we wish you all
the best,
Your ___ Care team

Followup Instructions:
___

In [490]:
edstays

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,F,WHITE,AMBULANCE,ADMITTED
1,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,F,WHITE,AMBULANCE,ADMITTED
2,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,F,WHITE,AMBULANCE,ADMITTED
3,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,F,WHITE,AMBULANCE,HOME
4,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,F,WHITE,AMBULANCE,ADMITTED
...,...,...,...,...,...,...,...,...,...
425082,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,M,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED
425083,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,F,WHITE,AMBULANCE,ADMITTED
425084,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,F,WHITE,WALK IN,ADMITTED
425085,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:56:00,F,UNKNOWN,UNKNOWN,ELOPED
425086,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,F,UNKNOWN,AMBULANCE,ADMITTED

In [157]:
hosp_adm[hosp_adm.subject_id.isin(cs)].admission_type.value_counts()

admission_type
EW EMER.                       4192
EU OBSERVATION                 3730
OBSERVATION ADMIT              2440
DIRECT OBSERVATION              398
DIRECT EMER.                    352
SURGICAL SAME DAY ADMISSION     297
URGENT                          269
ELECTIVE                        101
AMBULATORY OBSERVATION           79
Name: count, dtype: int64

In [268]:
icdp = pd.read_csv('mimic/mimic-iv-3.1/hosp/d_icd_procedures.csv.gz').set_index(['icd_version', 'icd_code'])

In [272]:
proc = pd.read_csv('mimic/mimic-iv-3.1/hosp/procedures_icd.csv.gz').join(icdp, on=['icd_version', 'icd_code'])

In [ ]:
rel_proc = ['Open biopsy of lung',
 'Closed endoscopic biopsy of lung',
 'Thoracoscopic lung biopsy',
 'Closed [percutaneous] [needle] biopsy of lung','Other bronchoscopy', 'Fiber-optic bronchoscopy', 'Computerized axial tomography of thorax',
 'Computerized Tomography (CT Scan) of Bilateral Lungs using Other Contrast, Unenhanced and Enhanced',
 'Computerized Tomography (CT Scan) of Chest, Abdomen and Pelvis using Other Contrast, Unenhanced and Enhanced', 'Transpleural thoracoscopy']

In [427]:
rel_icdp = icdp[icdp.long_title.isin(rel_proc)].reset_index().icd_code

In [439]:
cs3 = proc[proc.icd_code.isin(rel_icdp)].subject_id.unique()

In [441]:
hdx

         subject_id   hadm_id  seq_num icd_code  icd_version
0          10000032  22595853        1     5723            9
1          10000032  22595853        2    78959            9
2          10000032  22595853        3     5715            9
3          10000032  22595853        4    07070            9
4          10000032  22595853        5      496            9
...             ...       ...      ...      ...          ...
6364483    19999987  23865745        7    41401            9
6364484    19999987  23865745        8    78039            9
6364485    19999987  23865745        9     0413            9
6364486    19999987  23865745       10    36846            9
6364487    19999987  23865745       11     7810            9

[6364488 rows x 5 columns]

In [499]:
edstays

,subject_id,hadm_id,stay_id,intime,outtime,gender,race,arrival_transport,disposition
0,10000032,22595853.0,33258284,2180-05-06 19:17:00,2180-05-06 23:30:00,F,WHITE,AMBULANCE,ADMITTED
1,10000032,22841357.0,38112554,2180-06-26 15:54:00,2180-06-26 21:31:00,F,WHITE,AMBULANCE,ADMITTED
2,10000032,25742920.0,35968195,2180-08-05 20:58:00,2180-08-06 01:44:00,F,WHITE,AMBULANCE,ADMITTED
3,10000032,29079034.0,32952584,2180-07-22 16:24:00,2180-07-23 05:54:00,F,WHITE,AMBULANCE,HOME
4,10000032,29079034.0,39399961,2180-07-23 05:54:00,2180-07-23 14:00:00,F,WHITE,AMBULANCE,ADMITTED
...,...,...,...,...,...,...,...,...,...
425082,19999784,26194817.0,35692999,2119-06-18 14:21:00,2119-06-18 21:09:29,M,BLACK/AFRICAN AMERICAN,WALK IN,ADMITTED
425083,19999828,25744818.0,32917002,2149-01-08 09:11:00,2149-01-08 18:12:00,F,WHITE,AMBULANCE,ADMITTED
425084,19999828,29734428.0,30712109,2147-07-17 17:18:00,2147-07-18 17:34:00,F,WHITE,WALK IN,ADMITTED
425085,19999914,NaN,32002659,2158-12-24 11:41:00,2158-12-24 11:56:00,F,UNKNOWN,UNKNOWN,ELOPED
425086,19999987,23865745.0,34731548,2145-11-02 19:28:00,2145-11-02 22:59:00,F,UNKNOWN,AMBULANCE,ADMITTED

,subject_id,stay_id,seq_num,icd_code,icd_version,icd_title
0,10000032,32952584,1,4589,9,HYPOTENSION NOS
1,10000032,32952584,2,07070,9,UNSPECIFIED VIRAL HEPATITIS C WITHOUT HEPATIC ...
2,10000032,32952584,3,V08,9,ASYMPTOMATIC HIV INFECTION
3,10000032,33258284,1,5728,9,"OTH SEQUELA, CHR LIV DIS"
4,10000032,33258284,2,78959,9,OTHER ASCITES
...,...,...,...,...,...,...
899045,19999828,30712109,1,K632,10,Fistula of intestine
899046,19999828,32917002,1,E1110,10,Type 2 diabetes mellitus with ketoacidosis wit...
899047,19999828,32917002,2,Z7984,10,Long term (current) use of oral hypoglycemic d...
899048,19999914,32002659,1,R4182,10,"Altered mental status, unspecified"
899049,19999987,34731548,1,431,9,INTRACEREBRAL HEMORRHAGE

In [431]:
proc

,subject_id,hadm_id,seq_num,chartdate,icd_code,icd_version,long_title
0,10000032,22595853,1,2180-05-07,5491,9,Percutaneous abdominal drainage
1,10000032,22841357,1,2180-06-27,5491,9,Percutaneous abdominal drainage
2,10000032,25742920,1,2180-08-06,5491,9,Percutaneous abdominal drainage
3,10000068,25022803,1,2160-03-03,8938,9,Other nonoperative respiratory measurements
4,10000117,27988844,1,2183-09-19,0QS734Z,10,Reposition Left Upper Femur with Internal Fixa...
...,...,...,...,...,...,...,...
859650,19999840,21033226,5,2164-09-16,0331,9,Spinal tap
859651,19999840,26071774,1,2164-07-25,8891,9,Magnetic resonance imaging of brain and brain ...
859652,19999840,26071774,2,2164-07-25,8841,9,Arteriography of cerebral arteries
859653,19999987,23865745,1,2145-11-07,8841,9,Arteriography of cerebral arteries
859654,19999987,23865745,2,2145-11-02,9671,9,Continuous invasive mechanical ventilation for...

In [503]:
labs = pd.read_csv('mimic/mimic-iv-3.1/hosp/labevents.csv.gz')

:

In [388]:
[p for p in proc.long_title.unique() if 'biopsy' in p and 'lung' in p]

['Open biopsy of lung',
 'Closed endoscopic biopsy of lung',
 'Thoracoscopic lung biopsy',
 'Closed [percutaneous] [needle] biopsy of lung']

In [391]:
[p for p in proc.long_title.unique() if 'broncho' in p]

['Other bronchoscopy', 'Fiber-optic bronchoscopy']

In [418]:
[p for p in proc.long_title.unique() if 'tomography' in p.lower() and ('lung' in p.lower() or 'thor' in p.lower() or 'chest' in p.lower())]

['Computerized axial tomography of thorax',
 'Computerized Tomography (CT Scan) of Bilateral Lungs using Other Contrast, Unenhanced and Enhanced',
 'Computerized Tomography (CT Scan) of Chest, Abdomen and Pelvis using Other Contrast, Unenhanced and Enhanced']

In [401]:
[p for p in proc.long_title.unique() if 'thoracoscopy' in p]

['Transpleural thoracoscopy']

In [289]:
pd.read_csv('mimic/mimic-iv-3.1/hosp/omr.csv.gz')

         subject_id   chartdate  seq_num      result_name result_value
0          10000032  2180-04-27        1   Blood Pressure       110/65
1          10000032  2180-04-27        1     Weight (Lbs)           94
2          10000032  2180-05-07        1      BMI (kg/m2)         18.0
3          10000032  2180-05-07        1  Height (Inches)           60
4          10000032  2180-05-07        1     Weight (Lbs)        92.15
...             ...         ...      ...              ...          ...
7753022    19999828  2148-02-26        1   Blood Pressure       115/79
7753023    19999828  2148-04-29        1   Blood Pressure       105/67
7753024    19999828  2148-07-22        1   Blood Pressure       104/76
7753025    19999828  2148-10-19        1   Blood Pressure       112/73
7753026    19999828  2148-11-23        1   Blood Pressure       108/80

[7753027 rows x 5 columns]